<div class="jumbotron">
    <table>
        <tr>
            <th>id</th>
            <th>Nombre</th>
            <th>Localidad</th>
        </tr>
        <?php
            foreach ($personas as $persona) {
                echo ('<tr>');
                echo ('<td>');
                echo ($persona->getId());
                echo ('</td>');  
                echo ('<td>');
                echo ($persona->getNombre());
                echo ('</td>'); 
                echo ('<td>');
                $localidad = $persona->getLocalidad();
                if ($localidad)
                {
                    echo ($localidad->getNombre());
                } else
                {
                    echo ('No def.');
                }    
                
                echo ('</td>');                 
                echo ('</tr>');
            }        
        ?>
    </table>
</div>
